#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Queue/OCRBilletParse.Queue.Api/OCRBilletParse.Queue.Api.csproj", "Queue/OCRBilletParse.Queue.Api/"]
RUN dotnet restore "Queue/OCRBilletParse.Queue.Api/OCRBilletParse.Queue.Api.csproj"
COPY . .
WORKDIR "/src/Queue/OCRBilletParse.Queue.Api"
RUN dotnet build "OCRBilletParse.Queue.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OCRBilletParse.Queue.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OCRBilletParse.Queue.Api.dll"]